---
title: "Estimating yield as a function of chill accumulation"
author: Katja Schiffers^a^, Cory Whitney^a^, Eduardo Fernandez^a^ and Eike Luedeling^a^ <br /> <small>^a^INRES-Horticultural Sciences, University of Bonn, Auf dem Huegel 6, 53121 Bonn, Germany <small/>
output:
  word_document: default
csl: acta-horticulturae.csl
---

<!-- Abstract for the IV International Symposium on Horticulture in Europe - SHE2020 https://www.actahort.org/members/symposiar?nr=507 
-->

<!-- Guidelines for authors: 
https://www.ishs.org/sites/default/files/page-documents/onlinesubmissionauthorsguide.pdf
-->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#packages in alphabetic order
library(chillR)
library(devtools)
library(dplyr)
library(ggplot2)
library(ggstance)
library(graphics)
library(kableExtra)
#devtools::install_github("hortibonn/pasitR")
library(pasitR)
library(plyr)
library(tidyverse) #tidyverse includes a number of useful packages
```

Data is often limited for assessing the relationship between temperatures and yield. We show how, despite this lack of data, we may still be able to make assessments and produce useful projections for farmers and decision makers. With the right tools this data limitation does not need to hinder our abilities to assess the relationships between temperature and yield. For coarse assessments a lot of data may not be necessary. We use the pasitR package in the R programming language to illustrate methods whereby we can embrace the inherent uncertainty in such assessments to overcome the need for preciseness. We show a potential method for dealing with important but also necessarily uncertain relationships in model forecasts. 

We offer an example of assessing yield given chill (Chill Portions) for sweet cherries (*Prunus avium* L.) 'Lapins' and 'Brooks' varieties. We developed procedures and incorported them into an R library called `pasitR` that we use for estimating yield as a function of chill accumulation. We tested this with data provided by the experimental orchard of the School of Agronomy at the Pontificia Universidad Catolica de Valparaiso and weather data obtained from a local weather station. 

The work demonstrates the possibility for generating forecasts of possible yields given chill. The functions are all stored in an open access repository (https://github.com/hortibonn/pasitR) and are free to use and modify. 
